#+title: Modules with Inert Variables

* Definitions
Fix a pair $m,n \ge 1$ throughout.  Let $\mathcal{S}_{n}$ act
diagonally on (ambient) polynomial ring
$\mathcal{A}_{m,n}=\mathbb{Q}[x_{11},\dots,x_{1n}, \dots, x_{m1},\dots,x_{mn}]$.
When the variables are organized as a matrix
\[
  \bm{x} =
  \begin{pmatrix}
    x_{11} & \cdots & x_{1n} \\
    \vdots & \ddots & \vdots \\
    x_{m1} & \cdots & x_{mn}
  \end{pmatrix},
\]
with the $i$-th row being the $it$-th set of variables
$\bm{x}_{i} = (x_{i1},\dots,x_{in})$, then the diagonal
$\mathcal{S}_{n}$-action can be thought of as left-multiplication on
$\bm{x}$.  We use Frobenius notation to write hook shaped partition
$(\mathrm{arm}+1,1^{\mathrm{leg}})$ as
$(\mathrm{arm} \mid \mathrm{leg})$.  In this note, we study
$\mathcal{S}_{n}$-modules $\mathcal{M}_{(a|b)}$ and $\mathcal{S}_{(a|b)}$ for hooks $(a|b) \vdash n$.

We need two ingredients to construct these modules: an analogue of
Vandermonde determinant $\bm{D}_{(a|b)}$ as ``generator'' and
polarization operators $E_{ii'}^{(r)}$ that allow us to move between
sets of variables.  We make use of degree $0$ elements
$\theta_{1},\dots,\theta_{n}$.  For a set of variables
$\bm{x}_{i} = (x_{i1},\dots,x_{in})$, define for each hook $(a|b) \vdash n$,
\[
  \bm{D}_{(a|b)}(x_{i1},\dots,x_{in}) = \det
  \begin{pmatrix}
    \theta_{1} & 1 & x_{i1} & \cdots & \widehat{x_{i1}^{a}} & \cdots & x_{i1}^{n-1} \\
    \theta_{2} & 1 & x_{i2} & \cdots & \widehat{x_{i2}^{a}} & \cdots & x_{i2}^{n-1} \\
    \vdots & \vdots & \vdots & \ddots & \vdots & \ddots & \vdots \\
    \theta_{n} & 1 & x_{in} & \cdots & \widehat{x_{in}^{a}} & \cdots & x_{in}^{n-1} \\
  \end{pmatrix}
\]
where $\widehat{-}$ means that column is omitted.  Let
$\bm{D}_{(a|b)} = \bm{D}_{(a|b)}(x_{11},\dots,x_{1n})$.
\emph{Polarization operators} are defined by
\[
  E^{(r)}_{ii'} = \sum_{j=1}^{n} x_{i'j} \frac{\partial^{r}}{\partial_{x_{ij}^{r}}},
  \quad i,i' \in [m], r \ge 1.
\]
For each hook $(a|b) \vdash n$, the module
$\mathcal{M}_{(a|b)}$ is the smallest module containing
$\bm{D}_{(a|b)}$ and closed under partial differentiation and
polarization.

{{< lemma >}}
  Polarization commutes with $\mathcal{S}_{n}$-action, i.e., if $f \in \mathcal{A}_{m,n}$,
  then for $\sigma \in \mathcal{S}_{n}$  and for any $i,i' \in [m]$ and $r \ge 1$, we have
  \[
    E_{ii'}^{(r)} \sigma f = \sigma E_{ii'}^{(r)} f.
  \]
{{< /lemma >}}
{{< proof >}}
  The polarization operator can be written as
  \[
    E_{ii'}^{(r)} = \sum_{j=1}^{n} x_{i'j} \frac{\partial^{r}}{\partial x_{ij}^{r}} = \sum_{j=1}^{n} x_{i'\sigma(j)} \frac{\partial^{r}}{\partial x_{i\sigma(j)}^{r}}.
  \]
  This completes the proof.
{{< /proof >}}

* Examples
Let $m = n =3$ and name the variables
\[
  \begin{pmatrix}
    x_{1} & x_{2} & x_{3} \\
    y_{1} & y_{2} & y_{3} \\
    z_{1} & z_{2} & z_{3}
  \end{pmatrix}.
\]
The "Vandermondes" are
\[
\begin{aligned}
  \bm{D}_{(2|0)}
  &= \det
    \begin{pmatrix}
      \theta_{1} & 1 & x_{1} \\
      \theta_{2} & 1 & x_{2} \\
      \theta_{3} & 1 & x_{3}
    \end{pmatrix} = (1-(12)+(13)) \cdot \theta_{1}(x_{3}-x_{2}), \\
  \bm{D}_{(1|1)} &= \det
                   \begin{pmatrix}
                     \theta_{1} & 1 & x_{1}^{2} \\
                     \theta_{2} & 1 & x_{2}^{2} \\
                     \theta_{3} & 1 & x_{3}^{2}
                   \end{pmatrix} = (1-(12)+(13)) \cdot \theta_{1}(x_{3}^{2}-x_{2}^{2}), \\
  \bm{D}_{(0|2)}
  &= \det
    \begin{pmatrix}
      \theta_{1} & x_{1} & x_{1}^{2} \\
      \theta_{2} & x_{2} & x_{2}^{2} \\
      \theta_{3} & x_{3} & x_{3}^{2}
    \end{pmatrix}
                      = (1-(12)+(13)) \cdot \theta_{1}(x_{2}x_{3}^{2}-x_{2}^{2}x_{3}).
\end{aligned}
\]

We consider polarization.

Let $E_{u} = \sum_{j=1}^{n} \frac{\partial}{\partial u_{j}}$. Note
\[
\begin{aligned}
  E_{x} \theta_{1} (x_{2}x_{3}^{2} - x_{2}^{2}x_{3})
  &= \theta_{1}(x_{3}^{2} + 2x_{2}x_{3} - 2x_{2}x_{3} - x_{2}^{2}) \\
  &= \theta_{1}(x_{3}^{2} - x_{2}^{2}) \\
  E_{x} \theta_{1}(x_{3}^{2} - x_{2}^{2})
  &= 2 \theta_{1}(x_{3} - x_{2}).
\end{aligned}
\]
It follows that
$E_{x} \bm{D}_{(0 \mid 2)} = \bm{D}_{(1|1)}$ and
$E_{x} \bm{D}_{(1|1)} = 2 \bm{D}_{(2|0)}$.

For hook $(2 \mid 0)$, we have
\[
  E_{xy}^{(1)} \theta_{1}(x_{3}-x_{2}) = \theta_{1}(y_{3}-y_{2}).
\]

For hook $(1 \mid 1)$, we have
\[
\begin{aligned}
  E_{xy}^{(1)} \theta_{1}(x_{3}^{2}-x_{2}^{2})
  &= 2 \theta_{1}(x_{3}y_{3} - x_{2}y_{2}) \\
  E_{xy}^{(2)} \theta_{1}(x_{3}^{2}-x_{2}^{2})
  &= 2 \theta_{1}(y_{3}^{2}-y_{2}^{2}) \\
  E_{xy}^{(1)}E_{xy}^{(1)} \theta_{1}(x_{3}^{2}-x_{2}^{2})
  &= 2 \theta_{1}(y_{3}^{2} - y_{2}^{2}).
\end{aligned}
\]

For hook $(0 \mid 2)$, we have
\[
\begin{aligned}
  E_{xy}^{(1)} \theta_{1}(x_{2}x_{3}^{2}-x_{2}^{2}x_{3})
  &=  \theta_{1}(x_{3}^{2}y_{2} + 2x_{2}x_{3}y_{3} - 2x_{2}x_{3}y_{2} -
    x_{2}^{2}y_{3}) \\
  E_{xy}^{(2)} \theta_{1}(x_{2}x_{3}^{2}-x_{2}^{2}x_{3})
  &=  \theta_{1}(2x_{2}y_{3} - 2y_{2}x_{3}) \\
  E_{xy}^{(1)} E_{xy}^{(1)} \theta_{1}(x_{2}x_{3}^{2}-x_{2}^{2}x_{3})
  &=  \theta_{1}(2x_{3}y_{2}y_{3} + 2x_{3}y_{2}y_{3} + 2x_{2}y_{3}^{2} -
    2x_{3}y_{2}^{2} - 2x_{2}y_{2}y_{3} - 2x_{2}y_{2}y_{3} ) \\
  &= \theta_{1}(4(x_{3}-x_{2})y_{2}y_{3} + 2 x_{2}y_{3}^{2} - 2
    x_{3}y_{2}^{2})\\
  E_{xy}^{(2)} E_{xy}^{(1)} \theta_{1}(x_{2}x_{3}^{2}-x_{2}^{2}x_{3})
  &= \theta_{1}(2y_{2}y_{3} - 2 y_{2}y_{3}) \\
  E_{xy}^{(1)}E_{xy}^{(1)} E_{xy}^{(1)}
  \theta_{1}(x_{2}x_{3}^{2}-x_{2}^{2}x_{3})
  &= \theta_{1}(4y_{2}y_{3}^{2} - 4 y_{2}^{2}y_{3} + 2 y_{2}y_{3}^{2} - 2 y_{2}^{2}y_{3})\\
  &= 6 \theta_{1}(y_{2}y_{3}^{2} - y_{2}^{2}y_{3}).
\end{aligned}
\]

* Conjectures
{{< conjecture >}}
  For each $n \ge 1$, the space of coinvariant (quotient) space
  $\mathcal{E}_{n}$ is isomorphic to $\mathcal{S}_{1^{n}}$ as $\mathcal{S}_{n}$-modules.
{{< /conjecture >}}

{{< conjecture >}}
  For each $n \ge 1$,
  \[
  \begin{aligned}
    (id \otimes e_{1}^{\perp}) \mathcal{S}_{(n)}
    &= \sum_{b=0}^{n-2} \mathcal{S}_{(n - 1 - b \mid b)} \\
    (e_{1}^{\perp} \otimes id) \mathcal{S}_{(1^{n})}
    &= \sum_{a = 1}^{n-1} \mathcal{S}_{(a \mid n-1-a)}.
  \end{aligned}
  \]
{{< /conjecture >}}

* The "Alternating" space $\mathcal{S}_{1^{n}}$
These two properties are extracted from Francois GarsiaFest talk.  They
help with Conjecture 2.
- The space $\mathcal{S}_{1^{n}}$ is also the smallest module containing
  Vandermonde determinant $V_{n}$ and closed under partial derivatives
  and polarizations.
- The space $(e_{1}^{\perp} \otimes Id) \mathcal{S}_{1^{n}}$ is the smallest module
  containing the determinant \[\det\left( 1, x_{i},
  x_{i}^{2},\dots,x_{i}^{n-2}, \theta_{i}x_{i}^{n-2} \right)_{i=1,\dots,n}, \]
  and closed under partial derivatives and polarizations.

For three sets of variables, the dimension of $\mathcal{S}_{1^{n}}$ is
$2^{n}(n+1)^{n-1}$.

* References
