#+title: Lagrange Inversion

A formal power series $f$ is has a compositional inverse if its
constant term is invertible.

{{< theorem >}}
Suppose $F \in R[[x]]$ is a formal power series with a compositional
inverse $F^{(-1)}$.  Then for any $k,n \in \mathbb{Z}$, we have
\[
n[x^{n}] F^{(-1)}(x)^{k} = k [x^{-k}] F(x)^{-n},
\]
where $F(x)^{-n}$ exists as a Laurent series.  Equivalently, if
$f \in R[[x]]$ can be expressed as $f = x \phi(f)$ for some
multiplicatively invertible series $\phi(\lambda) \in R[[\lambda]]$, then for any
$n,k \in \mathbb{Z}$
\[
n[x^{n}] f(x)^{k} = k [\lambda^{n-k}] \phi(\lambda)^{n}.
\]
{{< /theorem >}}

{{< example >}}
Suppose $r \in K[[x]]$ is a formal power series. If $r = x F(r)$ for
some $F \in K[[x]]$ with invertible $F(0)$, then its the
compositional inverse is
\[ s(x) = r^{-1}(x) = x F(x)^{-1}. \]

This is easy to verify since $r(s) = x G(r(s))^{-1} G(x) = x$ and
$s(r) = r (r/x)^{-1} = x$.
{{< /example >}}

{{< example >}}
Suppose $r \in K[[x]]$ is a formal power series in the form
$r = x F(x)$ for some $F \in K[[x]]$ with invertible $F(0)$ and
$s \in K[[x]]$ is its compositional inverse. Then $x = s F(s)$
implies $s = x F(s)^{-1}$. Hence, by Lagrange inversion
\[ [x^{n}]s = \frac{1}{n} [s^{n-1}] F(s)^{-n}. \]
{{< /example >}}

{{< example >}}
Suppose $r,s \in K[[x]]$ are inverses and $r = xF(x)$ and
$s = xG(x)$ with invertible $F(0)$ and $G(0)$. Then
$x = r G(r) = s F(s)$. Furthermore, $s = x F(s)^{-1}$ and
\[ [x^{n}] G(x) = [x^{n+1}] s = \frac{1}{n+1} [s^{n}]
  F(s)^{-n-1}. \]
Equivalently we have
\[ [x^{n}]G(x) = [r^{n+1}] x = \frac{1}{n+1} [r^{n}] F(x)^{-n-1}, \]
since $r = x F(x)$ implies $x = r F(x)^{-1}$.
{{< /example >}}
