#+title: Research
#+weight: 100

My research is in algebraic combinatorics with a focus on diagonal harmonics and their generalizations. I am working towards a proof of the \(t=0\) case of superspace conjecture proposed by [[https://arxiv.org/abs/1902.08966][Mike Zabrocki in 2019]].

Let super polynomial ring be \(SR_{n} = \mathbb{Q}[x_{1},\dots,x_{n},\theta_{1},\dots,\theta_{n}]\) with \(x\)'s commuting and \(\theta\)'s anti-commuting. The symmetric group \(\mathcal{S}_{n}\) acts on \(SR_{n}\) diagonally by permuting each set of variables simultaneously.  Let \(SI_{n}\) be the ideal generated by non-constant super power sums \(p_{\epsilon,k} = \sum_{i=1}^{n} \theta_{i}^{\epsilon} x_{i}^{k}\) for each \(\epsilon \in \{0,1\}\) and for each \(k \ge 0\). Then the quotient \(SC_{n} = SR_{n} / SI_{n}\) is a well-defined module commonly known as super coinvariant space. Zabrocki conjectured that its graded Frobenius series is
\[
  \sum_{k=1}^{n} z^{n-k} \sum_{S \in STY(n)} q^{maj(S) + \binom{k}{2} - k(n-k)} \left[ \begin{smallmatrix} des(S) \\ n-k \end{smallmatrix} \right] s_{sh(T)}.
\]
It is known that packed words index their bases.

One can approach this problem by looking at a certain orthogonal complement of the ideal \(SI_{n}\). This is often known as the harmonics side of the problem. Define an inner product on \(SR_{n}\) by \( \langle f, g \rangle = (f(\partial)g)(0,\dots,0) \). The super harmonics space is \(SH_{n} = SI_{n}^{\perp}\). Note \(SH_{n}\) and \(SC_{n}\) are isomorphic \(\mathcal{S}_{n}\) modules.

The objects mentioned above are superspace analogues of the classic coinvariant and harmonics of the symmetric group.  At the beginning of my PhD studies, two groups of researchers independently proved the alternating portion of the conjecture using analogues of polarization operators. However both groups found it difficult to construct a leading term argument to the space has the right dimension.

Inspired by these efforts and Francois Bergeron's [[https://arxiv.org/abs/2005.00924][diagonal harmonics in infinitely many sets of variables]], I started constructing a basis by generalizing the higher Specht basis of the classic space. My contribution to the problem is a slight change of perspective to think about polarization operators as super symmetric polynomials under the equivalence of the classic invariant ideal \(I_{n} = \langle e_{k}(x_{1},\dots,x_{n}) : k \ge 1 \rangle\). Combined with a bijection between packed words and tuples \((\alpha,S,T)\) where \(\alpha\) are certain weakly increasing exponent vectors and \(S,T\) are tableaux of the same shape, I constructed a set of polynomials and conjectured that they are linearly independent.
