#+title: Diagonal harmonics in superspaces
#+weight: 110

In this project, I focus on the diagonal (super) /harmonics/ of superspace \(\mathrm{SH}_{n}\) in one set of commuting variables.  Ideally, I would find a /higher Specht basis/ for \(\mathrm{SH}_{n}\) and prove a conjecture by Zabrocki related to the representations side of the Delta Theorem.  Assuming familiarity with diagonal harmonics and the Delta conjectures, you can find my mot≈givation and the background on this problem in the following sections.

The most promising conjecture that I have computationally verified up to \(n=6\) is the following:  \(\mathrm{SH}_{n}\) decomposes as
\begin{equation}
\mathrm{SH}_{n} = H_{0} \oplus \cdots \oplus H_{n-1},
\end{equation}
where each \(H_{k}\) is spanned by applying monomial differential operators in \(x\)-variables /only/ to the \(\theta\)-degree \(k\) alternating component in \(\mathrm{SH}_{{n}}\).  It is known that ≈gsome \(H_{k}\) are not "cyclic" in the sense that their alternating component has dimension greater than \(1\).

* Superspace (in one set of commuting variables)
Consider the polynomial ring \(\mathrm{SS}_{n} = \mathbb{Q}[\theta_{1},\dots,\theta_{n},x_{1},\dots,x_{n}]\) with anti-commuting (Fermionic) variables \(\theta_{1},\dots,\theta_{n}\) and commuting (Bosonic) variables \(x_{1},\dots,x_{n}\). The symmetric group \(\mathfrak{S}_{n}\) act on \(\mathrm{SS}_{n}\) diagonally by
\begin{equation}
  \sigma \cdot f = f(\theta_{\sigma(1)},\dots,\theta_{\sigma(n)},x_{\sigma(1)},\dots,x_{\sigma(n)}).
\end{equation}

Let \(\mathrm{SI}_{n}\) be the ideal generated by non-constant symmetric polynomials in
\(\Omega_{n}\).  Since \(\mathrm{SI}_{n}\) is invariant under the \(\mathfrak{S}_{n}\)-action, the quotient ring
\(\mathrm{SC} = \mathrm{SS}_{n}/\mathrm{SI}_{n}\) is a well-defined submodule.

It is conjectured by [[https://arxiv.org/abs/1902.08966][Zabrocki (2019)]] that its quotient ring has graded Frobenius series
\begin{equation}
  \label{eq:mike-superspace-t-to-0}
  \mathrm{grFrob}(\mathrm{SC}_{n};q,t,z) = \left(\Delta'_{e_{n-1} + e_{n-2}z + \cdots + z^{n-1}} e_{n} \right) \bigg|_{t=0}.
\end{equation}

The super harmonics \(\mathrm{SH}_{n}\) of \(\mathrm{SC}_{n}\) is defined to be the /subspace/ of \(\mathrm{SS}_{n}\)
\begin{equation}
\mathrm{SH}_{n} = \{ f \in \mathrm{SS}_{n} : g(\partial) f = 0 \textrm{ for all } g \in \mathrm{SH}_{n} \}.
\end{equation}

* Emacs                                                            :noexport:
# Local Variables:
# eval: (org-cdlatex-mode)
# eval: (prettify-symbols-mode)
# eval: (my/add-to-prettify-symbols-alist-latex)
# End:
